# fly.toml app configuration file generated for sf-camp on 2023-11-22T14:59:12+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "sf-camp"
primary_region = "nrt"

[build]

[env]
  PORT = "8081"
  SHOPIFY_APP_URL = "https://sf-camp.fly.dev"
  SHOPIFY_API_KEY = "1f44817248ad542b00e203fda724a8b7"
  SCOPES = "write_products"

[http_service]
  internal_port = 8081
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
