# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "sf-camp"
client_id = "1f44817248ad542b00e203fda724a8b7"
application_url = "https://accessory-editorials-gonna-dock.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://accessory-editorials-gonna-dock.trycloudflare.com/auth/callback",
  "https://accessory-editorials-gonna-dock.trycloudflare.com/auth/shopify/callback",
  "https://accessory-editorials-gonna-dock.trycloudflare.com/api/auth/callback",
  "https://accessory-editorials-gonna-dock.trycloudflare.com/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "warpjapan-plus-camp.myshopify.com"
